### ISSUE TITLE
Start with a basic usage notebook

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphs/JuliaGraphsTutorials#1]
This issue tracks https://github.com/JuliaGraphs/LightGraphs.jl/issues/519, which should be closed by now.

**Comment by juliohm** [comment]
@sbromberger , @jpfairbanks , did I miss anything in this basic tutorial? Anything else that you would like to see in there before I move to the next notebook?

https://github.com/JuliaGraphs/JuliaGraphsTutorials/blob/master/Basics.ipynb

P.S.: Do you know why GitHub is failing to show some of the SVG in the notebook? It is showing correctly here on my laptop.

**Comment by sbromberger** [comment]
The first broken link shows a bad svg. Here's a screenshot:
<img width="1079" alt="screen shot 2017-03-21 at 18 59 56" src="https://cloud.githubusercontent.com/assets/941359/24178803/a06431a6-0e68-11e7-8596-ac4de7338e0c.png">

**Comment by juliohm** [comment]
Have no idea why, everything shows correctly locally before I push to GitHub.

**Comment by juliohm** [comment]
Closing this issue and moving to the next notebook later this weekend...
