### ISSUE TITLE
Cannot install GraphPlot

### ISSUE THREAD

**Issue by eschnett** [JuliaGraphs/JuliaGraphsTutorials#10]
The first example (`Basics`) uses the two packages `LightGraphs` and `GraphPlot`. The latter does not seem to work with Julia 1.0.

**Comment by simonschoelly** [comment]
`GraphPlots.jl` was recently updated, so that should work now. The tutorial might also need an upgrade though.

**Comment by juliohm** [comment]
Thank you all for reporting. The notebook is working fine. I've rerun it and pushed again to master.
