### ISSUE TITLE
Is it possible to add annotations to edges of a SimpleDiGraph?

### ISSUE THREAD

**Issue by shayandavoodii** [JuliaGraphs/JuliaGraphsTutorials#18]
Hi, I have created a `SimpleDiGraph,` and I wish to annotate the edges of this graph, but I don't know how. Can you please help me with it?<br>
This is what my graph looks like, and I wish to annotate all of its edges:<br>
![image](https://user-images.githubusercontent.com/52105833/189900108-410fd4cc-ae7a-41d2-a65c-ae3ec1ca0b1d.png)

**Comment by juliohm** [comment]
Consider GraphMakie.jl for advanced graph plotting: https://graph.makie.org/stable/generated/plots
