### ISSUE TITLE
`UUndefVarError: descendents not defined` in DAG tutorial

### ISSUE THREAD

**Issue by miguelraz** [JuliaGraphs/JuliaGraphsTutorials#2]
Couldn't find the source function in the LightGraphs repo either.

**Comment by juliohm** [comment]
This is not a function, it is a variable defined in one of the cells. Are you running the notebook as is or modifying it?

**Comment by miguelraz** [comment]
Modified it - got the error. Thanks a lot.
Typo though:
`descendents` -> `descendants`.

**Comment by juliohm** [comment]
Thanks, I need to fix these small English typos at some point. Closing the issue.
