### ISSUE TITLE
Suggestion for an additional notebook

### ISSUE THREAD

**Issue by ghost** [JuliaGraphs/JuliaGraphsTutorials#9]
Based on a discussion with @sbromberger about a LightGraphs.jl subject (https://github.com/JuliaGraphs/LightGraphs.jl/issues/930) the idea was born to add my notebook to your tutorials. A download link is available at the bottom of the chat. What do you think about it?

**Comment by juliohm** [comment]
Hi @JuergenKanz, thank you for sharing. I will take a more careful look as soon as I have time. I should be back by the end of August after defending my PhD.

**Comment by juliohm** [comment]
@JuergenKanz sorry again for the delay. Could you maybe share again the notebook you had in mind? I couldn't access the Google Drive link in that issue.

Please feel free to submit a PR, and I'd be happy to review and merge.

**Comment by juliohm** [comment]
Closing the issue as I think the notebook was lost in the drive somewhere.
